=== ulve/lexsigmarium/static/army.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/army.schema.json",
  "title": "army",
  "description": "An AoS 4 Army for Lexsigmarium.net",
  "definitions": {
    "spellLore": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the spell lore"
        },
        "spells": {
          "type": "array",
          "description": "An array of spells",
          "items": {
            "type": "object",
            "$ref": "#/definitions/ability"
          }
        }
      }
    },
    "header": {
      "type": "object",
      "properties": {
        "icon": {
          "type": "string",
          "description": "What icon to show",
          "enum": [
            "rally",
            "defensive",
            "offensive",
            "shooting",
            "control",
            "movement",
            "special",
            "damaged"
          ]
        },
        "color": {
          "type": "string",
          "description": "The color corresponding to the phase",
          "enum": [
            "black",
            "yellow",
            "gray",
            "orange",
            "teal",
            "red",
            "eggplant",
            "green"
          ]
        },
        "text": {
          "type": "string",
          "description": "The text to be displayed. NOT markdown"
        }
      }
    },
    "ability": {
      "type": "object",
      "properties": {
        "header": {
          "type": "object",
          "$ref": "#/definitions/header",
          "description": "The header the an ability"
        },
        "name": {
          "type": "string",
          "description": "The name of the ability"
        },
        "declare": {
          "type": "string",
          "description": "The declare instructions. Supports markdown"
        },
        "effect": {
          "type": "string",
          "description": "the effect instructions. Supports markdown"
        },
        "keywords": {
          "type": "array",
          "description": "An array of abilities",
          "items": {
            "type": "string"
          }
        },
        "castingValue": {
          "type": "string",
          "description": "The casting value of the ability"
        },
        "chantingValue": {
          "type": "string",
          "description": "The chanting value of the ability"
        },
        "commandValue": {
          "type": "string",
          "description": "The command value of the ability"
        }
      }
    },
    "rangedWeapon": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the weapon"
        },
        "rng": {
          "type": "string",
          "description": "The range of the weapon"
        },
        "atk": {
          "type": "string",
          "description": "The attack value of the weapon"
        },
        "hit": {
          "type": "string",
          "description": "The hit value of the weapon"
        },
        "wnd": {
          "type": "string",
          "description": "The wound value of the weapon"
        },
        "rnd": {
          "type": "string",
          "description": "The rend value of the weapon"
        },
        "dmg": {
          "type": "string",
          "description": "The damage value of the weapon"
        },
        "abilities": {
          "type": "array",
          "description": "An array of abilities",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "meleeWeapon": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the weapon"
        },
        "atk": {
          "type": "string",
          "description": "The attack value of the weapon"
        },
        "hit": {
          "type": "string",
          "description": "The hit value of the weapon"
        },
        "wnd": {
          "type": "string",
          "description": "The wound value of the weapon"
        },
        "rnd": {
          "type": "string",
          "description": "The rend value of the weapon"
        },
        "dmg": {
          "type": "string",
          "description": "The damage value of the weapon"
        },
        "abilities": {
          "type": "array",
          "description": "An array of abilities",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "stats": {
      "type": "object",
      "properties": {
        "movement": {
          "type": "string",
          "description": "The move value"
        },
        "save": {
          "type": "string",
          "description": "The save value"
        },
        "control": {
          "type": "string",
          "description": "The control value"
        },
        "health": {
          "type": "string",
          "description": "The health value"
        },
        "banishment": {
          "type": "string",
          "description": "The banishment value"
        }
      }
    },
    "warscroll": {
      "type": "object",
      "properties": {
        "notes": {
          "type": "string",
          "description": "Notes about the warscroll. Supports markdown"
        },
        "name": {
          "type": "string",
          "description": "The name of the warscroll"
        },
        "subtitle": {
          "type": "string",
          "description": "The subtitle of the warscroll"
        },
        "faction": {
          "type": "string",
          "description": "The faction the warscroll belongs to"
        },
        "stats": {
          "type": "object",
          "description": "The main stats for the warscroll",
          "$ref": "#/definitions/stats"
        },
        "meleeWeapons": {
          "type": "array",
          "description": "An array of melee weapons",
          "items": {
            "type": "object",
            "$ref": "#/definitions/meleeWeapon"
          }
        },
        "rangedWeapons": {
          "type": "array",
          "description": "An array of ranged weapons",
          "items": {
            "type": "object",
            "$ref": "#/definitions/rangedWeapon"
          }
        },
        "options": {
          "type": "string",
          "description": "The options text. Supports markdown"
        },
        "abilities": {
          "type": "array",
          "description": "An array of abilities",
          "items": {
            "type": "object",
            "$ref": "#/definitions/ability"
          }
        },
        "primaryKeywords": {
          "type": "array",
          "description": "An array of primary keywords",
          "items": {
            "type": "string"
          }
        },
        "secondaryKeywords": {
          "type": "array",
          "description": "An array of secondary keywords",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "prayers": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the prayer"
        },
        "prayers": {
          "type": "array",
          "description": "An array of prayers",
          "items": {
            "type": "object",
            "$ref": "#/definitions/ability"
          }
        }
      }
    },
    "battleFormation": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the battle formation"
        },
        "abilities": {
          "type": "array",
          "description": "An array of abilities",
          "items": {
            "type": "object",
            "$ref": "#/definitions/ability"
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "description": "The name of the army"
    },
    "grandFaction": {
      "type": "string",
      "description": "The grand faction of the army"
    },
    "icon": {
      "type": "string",
      "description": "The icon of the army stored in 'static/img/icons/army' including the file extension"
    },
    "color": {
      "type": "string",
      "description": "The primary color for the army. Should be fairly dark since the text is white"
    },
    "battleTraits": {
      "type": "array",
      "description": "An array of battle traits for the army",
      "items": {
        "type": "object",
        "$ref": "#/definitions/ability"
      }
    },
    "battleFormations": {
      "type": "array",
      "description": "An array of battle formations for the army",
      "items": {
        "type": "object",
        "$ref": "#/definitions/battleFormation"
      }
    },
    "artefacts": {
      "type": "array",
      "description": "An array of artefacts for the army",
      "items": {
        "type": "object",
        "$ref": "#/definitions/ability"
      }
    },
    "spellLores": {
      "type": "array",
      "description": "An array of spell lores for the army",
      "items": {
        "type": "object",
        "$ref": "#/definitions/spellLore"
      }
    },
    "prayers": {
      "type": "array",
      "description": "An array of prayers for the army",
      "items": {
        "type": "object",
        "$ref": "#/definitions/prayers"
      }
    },
    "warscrolls": {
      "type": "array",
      "description": "An array of warscrolls for the army",
      "items": {
        "type": "object",
        "$ref": "#/definitions/warscroll"
      }
    }
  }
}

=== ulve/lexsigmarium/static/unitData/iron-jaws.json
{
    "$schema": "../army.schema.json",
    "title": "Iron Jaws",
    "icon": "iron-jaws.png",
    "color": "#315442",
    "grandFaction": "Destruction",
    "warscrolls": [
        {
            "name": "Wierdnob Shaman",
            "faction": "Iron Jaws",
            "stats": {
                "movement": "4\"",
                "save": "6+",
                "control": "2",
                "health": "6"
            },
            "rangedWeapons": [
                {
                    "name": "Green Puke",
                    "rng": "10\"",
                    "atk": "4",
                    "hit": "2+",
                    "wnd": "4+",
                    "rnd": "-",
                    "dmg": "D3",
                    "abilities": [
                        "Shoot in Combat"
                    ]
                }
            ],
            "meleeWeapons": [
                {
                    "name": "Waaagh! Staff",
                    "atk": "3",
                    "hit": "4+",
                    "wnd": "3+",
                    "rnd": "1",
                    "dmg": "D3"
                }
            ],
            "abilities": [
                {
                    "name": "Brutal Power",
                    "header": {
                        "icon": "special",
                        "color": "yellow",
                        "text": "Passive"
                    },
                    "effect": "Add 1 to this unit's power level while there are any friendly **IRONJAWZ** units that have 10 or more models wholly within 12\" of it."
                }
            ],
            "primaryKeywords": [
                "Hero",
                "Wizard(1)",
                "Infantry"
            ],
            "secondaryKeywords": [
                "Destruction",
                "IronJaws"
            ]
        }
    ]
}

=== ulve/lexsigmarium/old/Hedonites of Slaanesh.json
{
  "$schema": "../army.schema.json",
  "title": "Hedonites of Slaanesh",
  "grandFaction": "Chaos",
  "icon": "hedonites-of-slaanesh.png",
  "color": "#4B0A40",
  "battleTraits": [
    {
      "name": "An Excess of Depravity",
      "header": {
        "icon": "special",
        "color": "black",
        "text": "Start of Battle Round"
      },
      "declare": "Pick up to 3 friendly **HEDONITES OF SLAANESH** units to be the targets.",
      "effect": "The targets have the **EUPHORIC** keyword for the rest of the battle round.\n\n In addition, for each friendly unit you pick, give your opponent 1 **temptation dice**. Your opponent can use 1 **temptation dice** to replace 1 wound roll, 1 save roll, 1 ward roll or 1 run roll for a unit in their army with a 6, or they can use 2 **temptation dice** to replace 2 of the dice in a charge roll for a unit in their army with two 6s.\n\n Each time your opponent uses a **temptation dice**, they must roll it. On a 1-2, inflict D3 mortal damage on the unit for which the roll was replaced immediately after the ability used by that unit has been resolved.\n\n At the end of the battle round, any **temptation dice** that have not been used are lost."
    },
    {
      "name": "Euphoric Killers",
      "header": {
        "icon": "special",
        "color": "black",
        "text": "Passive"
      },
      "effect": "While a friendly unit has the **EUPHORIC** keyword:\n\n * That unit's weapons have **Crit (2 Hits)**.\n * That unit can use a RuN ability and still use **SHOOT** and/or **CHARGE** abilities later in the turn."
    }
  ],
  "battleFormations": [
    {
      "name": "Depraved Carneval",
      "abilities": [
        {
          "name": "The Ecstatic Throngs",
          "header": {
            "icon": "offensive",
            "color": "red",
            "text": "Passive"
          },
          "effect": "Add 1 to hit rolls for friendly **SYBARITE INFANTRY** units while they are damaged or if they had any models slain in the same turn."
        }
      ]
    }
  ],
  "spellLores": [
    {
      "name": "Lore of Extravagance",
      "spells": [
        {
          "name": "Sadistic Spite",
          "header": {
            "icon": "special",
            "color": "yellow",
            "text": "Your Hero Phase"
          },
          "declare": "Pick a friendly **HEDONITES OF SLAANESH WIZARD** to cast this spell, pick a visible friendly **EUPHORIC** unit to be the target, then make a casting roll of 2D6.",
          "effect": "The target's melee weapons have **Crit (Mortal)** instead of **Crit (2 Hits)** for the rest of the battle round.",
          "castingValue": "6",
          "keywords": ["Spell", "Unlimited"]
        }
      ]
    }
  ],
  "warscrolls": [
    {
      "name": "Fiends",
      "faction": "Hedonites of Slaanesh",
      "stats": {
        "movement": "10\"",
        "save": "5+",
        "control": "1",
        "health": "4"
      },
      "meleeWeapons": [
        {
          "name": "Deadly Pincers and Barbed Stringer",
          "atk": "4",
          "hit": "4+",
          "wnd": "3+",
          "rnd": "1",
          "dmg": "D3",
          "abilities": ["Anti-Monster(+1 rend)", "Companion"]
        }
      ],
      "abilities": [
        {
          "name": "Soporific Musk",
          "header": {
            "icon": "defensive",
            "color": "red",
            "text": "Once Per Turn (Army), Any Combat Phase"
          },
          "declare": "Pick an enemy unit in combat with this unit to be the target.",
          "effect": "Roll a dice. On a 4+, the target has **STRIKE-LAST** for the rest of the turn."
        },
        {
          "name": "Disruptive Song",
          "header": {
            "icon": "special",
            "color": "yellow",
            "text": "Passive"
          },
          "effect": "Subtract 1 from casting rolls and unbinding rolls for enemy **WIZARDS** while they are within 12\" of this unit."
        },
        {
          "name": "Beast",
          "header": {
            "icon": "control",
            "color": "eggplant",
            "text": "Passive"
          },
          "effect": "This unit has a maximum control score of 1."
        }
      ],
      "primaryKeywords": ["Beast", "Champion", "Ward(6+)"],
      "secondaryKeywords": ["Chaos", "Hedonites of Slaanesh", "Daemon"]
    },
    {
      "name": "Shalaxi Helbane",
      "faction": "Hedonites of Slaanesh",
      "stats": {
        "movement": "14\"",
        "save": "4+",
        "control": "5",
        "health": "16"
      },
      "meleeWeapons": [
        {
          "name": "ðŸ’€ Soulpoercer",
          "atk": "6",
          "hit": "2+",
          "wnd": "3+",
          "rnd": "2",
          "dmg": "3",
          "abilities": ["Anti-Hero(+1 rend)"]
        },
        {
          "name": "Impaling Claws",
          "atk": "2",
          "hit": "3+",
          "wnd": "3+",
          "rnd": "2",
          "dmg": "4"
        }
      ],
      "abilities": [
        {
          "name": "Battle Damaged",
          "header": {
            "icon": "damaged",
            "color": "black",
            "text": "Passive"
          },
          "effect": "While this unit has 10 or more damage points, the Attacks characteristic of its **Soulpiercer** is 4."
        },
        {
          "name": "Supernatural Grace",
          "header": {
            "icon": "defensive",
            "color": "green",
            "text": "Passive"
          },
          "effect": "Subtract 1 from hit rolls for combat attacks that target this unit."
        },
        {
          "name": "Refine Senses",
          "header": {
            "icon": "special",
            "color": "yellow",
            "text": "Your Hero Phase"
          },
          "declare": "Make a casting roll of 2D6.",
          "effect": "For the rest of the turn:\n\n * Add 1 to wound rolls for this unit's attacks that target enemy **HEROES**.\n * Add 1 to save rolls for attacks made by enemy **HEROES** that target this unit.",
          "castingValue": "4",
          "keywords": ["Spell"]
        },
        {
          "name": "Paramount Hunter",
          "header": {
            "icon": "movement",
            "color": "orange",
            "text": "Once Per Turn (Army), Reaction: Opponent declared a CHARGE ability for a HERO within 9\" of this unit"
          },
          "effect": "If this unit is not in combat, it can immediately move 2D6\". It can pass through the combat ranges of enemy units but it must end that move within Â½\" of that **HERO**. If it does so, this unit has charged, and that **HERO'S CHARGE** ability has no effect.",
          "keywords": ["Core", "Move", "Charge", "Rampage"]
        },
        {
          "name": "Excess of Violence",
          "header": {
            "icon": "offensive",
            "color": "red",
            "text": "Once Per Battle, Your Combat Phase"
          },
          "declare": "Pick a friendly non-**HERO HEDONITES OF SLAANESH** unit wholly within 12\" of this unit to be the target.",
          "effect": "The target can use 2 **FIGHT** abilities this turn. After the first is used, however, the target has **STRIKE-LAST** for the rest of the turn."
        }
      ],
      "primaryKeywords": [
        "Warmaster",
        "Unique",
        "Hero",
        "Monster",
        "Wizard(2)",
        "Ward(5+)"
      ],
      "secondaryKeywords": ["Chaos", "Hedonites of Slaanesh", "Daemon"]
    },
    {
      "name": "Symbaresh Twinsouls",
      "faction": "Hedonites of Slaanesh",
      "stats": {
        "movement": "6\"",
        "save": "4+",
        "control": "1",
        "health": "2"
      },
      "meleeWeapons": [
        {
          "name": "Merciless Weapons",
          "atk": "4",
          "hit": "3+",
          "wnd": "4+",
          "rnd": "1",
          "dmg": "1"
        }
      ],
      "abilities": [
        {
          "name": "Ego-Driven Excess",
          "header": {
            "icon": "defensive",
            "color": "green",
            "text": "Passive"
          },
          "effect": "If this unit did not charge this turn, subtract 1 from the Attacks characteristic of melee weapons used by enemy units while they are in combat with this unit."
        },
        {
          "name": "Fiendish Reflexes",
          "header": {
            "icon": "defensive",
            "color": "green",
            "text": "Passive"
          },
          "effect": "If this unit did not charge this turn, it has **WARD (5+)** while it is in combat."
        }
      ],
      "primaryKeywords": ["Infantry", "Champion"],
      "secondaryKeywords": ["Chaos", "Hedonites of Slaanesh", "Syrabite"]
    },
    {
      "name": "Fane of Slaanesh",
      "faction": "Hedonites of Slaanesh",
      "stats": {
        "movement": "-",
        "save": "4+",
        "control": "-",
        "health": "10"
      },
      "notes": "The following universal terrain abilities apply to this terrain feature (Terrain, 1.2):\n\n Cover, Impassable",
      "abilities": [
        {
          "name": "Damned Conduit",
          "header": {
            "icon": "special",
            "color": "yellow",
            "text": "Your Hero Phase"
          },
          "declare": "Pick a friendly **HEDONITES OF SLAANESH** unit wholly within 12\" of this terrain feature to be the target."
        }
      ],
      "primaryKeywords": ["Faction Terrain", "Ward(6+)"],
      "secondaryKeywords": ["Chaos", "Hedonites of Slaanesh"]
    }
  ]
}
